# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '002-tableView-MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 002-tableView-MVVM
pod 'Alamofire'
end
